services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
      secrets:
        - jfrog_user
        - jfrog_token
    volumes:
      - ./:/usr/src/languagemodelcommon
    container_name: languagemodelcommon_dev
    working_dir: /usr/src/languagemodelcommon
    env_file:
      - docker.env

secrets:
  jfrog_user:
    environment: JFROG_READ_USER
  jfrog_token:
    environment: JFROG_READ_TOKEN
