services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/usr/src/languagemodelcommon
#      - ../oidc-auth-lib/oidcauthlib:/usr/local/lib/python3.12/site-packages/oidcauthlib:ro
      #      - ../langchain-ai-skills-framework/langchain_ai_skills_framework:/usr/local/lib/python3.12/site-packages/langchain_ai_skills_framework:ro
    container_name: languagemodelcommon_dev
    working_dir: /usr/src/languagemodelcommon
    env_file:
      - docker.env
